inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/{bundle,rails,rake,setup}
    - config/**/*
    - db/**/*
    - docker/**/*
    - vendor/**/*
  NewCops: enable

require:
  - rubocop-rails
