inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/{bundle,rails,rake,setup}
    - config/**/*
    - db/schema.rb
    - docker/**/*
    - vendor/**/*
  NewCops: enable

# specのexampleの行数を制限するルール。だが、デフォルトの5行はさすがに実用的じゃない。
# 15行でも多分厳しいので、必要に応じて調整してよさそう。
RSpec/ExampleLength:
  Max: 15

# シンボル(＝ステータスメッセージ)はここで自動生成されていて、変更されうるので数
# 値(＝ステータスコード)を直に使う。
# https://github.com/rack/rack/blob/main/lib/rack/utils.rb#L481-L484
RSpec/Rails/HttpStatus:
  EnforcedStyle: numeric

Style/BlockComments:
  Exclude:
    # 適切な使い方で、自動修正してもおかしいだけ。
    - spec/spec_helper.rb

# 全てのクラス・モジュールの上にコメントを強制する必要はないと思う。
Style/Documentation:
  Enabled: false

# 全ファイルにマジックコメントを求めるのはやりすぎかな。
# 本当に文字列のデフォルトが不変になるのであれば検討。
Style/FrozenStringLiteralComment:
  Enabled: false

require:
  - rubocop-rails
  - rubocop-rspec
