inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/{bundle,rails,rake,setup}
    - config/**/*
    - db/**/*
    - docker/**/*
    - vendor/**/*
  NewCops: enable

Style/BlockComments:
  Exclude:
    # 適切な使い方で、自動修正してもおかしいだけ。
    - spec/spec_helper.rb

# 全てのクラス・モジュールの上にコメントを強制する必要はないと思う。
Style/Documentation:
  Enabled: false

# 全ファイルにマジックコメントを求めるのはやりすぎかな。
# 本当に文字列のデフォルトが不変になるのであれば検討。
Style/FrozenStringLiteralComment:
  Enabled: false

require:
  - rubocop-rails
