# slim だと rails の依存エラー
FROM ruby:3.2.0-buster
RUN gem install bundler && \
    gem install rails -v "7.0.4"
RUN useradd -ms /bin/bash -u 1000 dev-user && \
    mkdir /app && chown 1000:1000 /app
USER 1000
RUN bundle config set path vendor/bundle
