---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/echo":
    get:
      summary: Simple Echo
      tags:
      - Echo
      responses:
        '200':
          description: echo
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
