development:
  basic_authenticate_user: <%= ENV['HTTP_BASIC_AUTHENTICATE_USER'] %>
  basic_authenticate_password: <%= ENV['HTTP_BASIC_AUTHENTICATE_PASSWORD'] %>
  jwt_hmac_secret: <%= ENV['JWT_HMAC_SECRET'] %>

test:
  basic_authenticate_user: <%= ENV['HTTP_BASIC_AUTHENTICATE_USER'] %>
  basic_authenticate_password: <%= ENV['HTTP_BASIC_AUTHENTICATE_PASSWORD'] %>
  jwt_hmac_secret: <%= ENV['JWT_HMAC_SECRET'] %>

production:
  basic_authenticate_user: <%= Rails.application.credentials.http_basic_authenticate.user %>
  basic_authenticate_password: <%= Rails.application.credentials.http_basic_authenticate.password %>
  jwt_hmac_secret: <%= Rails.application.credentials.jwt_hmac_secret %>

staging:
  basic_authenticate_user: <%= Rails.application.credentials.http_basic_authenticate.user %>
  basic_authenticate_password: <%= Rails.application.credentials.http_basic_authenticate.password %>
  jwt_hmac_secret: <%= Rails.application.credentials.jwt_hmac_secret %>
